### ISSUE TITLE
No hosts found

### ISSUE THREAD

**Issue by mattlyons0** [ethanpil/dyndns-cpanel#3]
It may be worth noting that for some reason under certain server configurations 'customonly' must be set to 0 in order to find subdomain records. This is regarding line 209 https://github.com/ethanpil/dyndns-cpanel/blob/master/dyndns.php#L209

It might be useful to put this in the error message or in the readme.

**Comment by ethanpil** [comment]
Thanks for the feedback. Do you know which circumstances might require this?

**Comment by mattlyons0** [comment]
I have a shared server with eleven2, I made the sub domain through the cpanel web interface and for whatever reason the real domains (ex sub.example.com, example.com) aren't listed as custom records. But things like autodiscover.sub.example.com and autodiscover.example.com are listed as custom.

**Comment by ethanpil** [comment]
Done. thanks.
